on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # No 'path' needed as this is the repo root
          package-name: "@kreozalabs/styles"
          release-type: node

      # Example: Publishing to NPM after release
      - name: checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4

      - name: setup node
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"

      - name: publish to npm
        if: ${{ steps.release.outputs.release_created }}
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
